### ISSUE TITLE
Issue after deploying project on HoloLens 2

### ISSUE THREAD

**Issue by bolebalazs** [HL2-DINO/DINO-Unity#1]
Hi!

We try to implement your HoloLens 2 object tracking solution, but after deploying it on HoloLens 2 device we have an issue with the application (we can start the application on HoloLens 2, but it does not show anything). We used Unity 2021 branch, VS 2019, Unity 2021.3.2f1.

You could also contact me on bolemanyibalazs@gmail.com. 

I would be really glad for your help since it seems to be a really interesting project.

Regards,
Balazs

**Comment by hiqb217** [comment]
Hi! Could you please try using VS 2022 as specified in the [README](https://github.com/HL2-DINO/DINO-Unity/blob/unity-21/README.md#requirements) instructions? Please ensure everything else is set up as described and try re-deploying. Hope that fixes your issue

**Comment by bolebalazs** [comment]
Hi!
I tried VS 2022 as well, but I still have this issue. I am pretty sure that everything else is set up as described.

**Comment by hiqb217** [comment]
Hi! Just to run through some potential sticking points and to confirm your setup, could you confirm you have:

- [ ] Enabled Research Mode on the HoloLens 2 [tutorial](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/research-mode#enabling-research-mode-hololens-first-gen-and-hololens-2)
- [ ] In Unity, set `Visual Studio Version` to Visual Studio 2022, set `Minimum Platform Version` to `10.0.1024.0` or something newer
- [ ] In Unity, set the Architecture to `ARM 64-bit`
- [ ] Launched your .sln with VS 2022
- [ ] In your .sln file, Updated the `Package.appxmanifest` [as shown in the README](https://github.com/HL2-DINO/DINO-Unity/blob/unity-21/README.md#getting-started)
- [ ] In your .sln file, under the DINO-Unity 21 project properties, ensured that the platform toolset is `Visual Studio 2022 (v143)
- [ ] After having set all of these up, could you switch the scene you're building to Scenes/SampleScene from Unity as a test to see if that changes anything?

I'm also assuming no changes to the source code / overall setup of the project? Could you post if you have made any changes to either the DLL or to the Unity side project (source code or scene)?

**Comment by bolebalazs** [comment]
Hi, thanks for your suggestions. Somehow the checkboxes are inactive for me (I cannot tick them), but all of the point you mentioned are confirmed, I made no changes in the scripts and the project. I tried SampleScene as well, but it also doesn't work (same issue as in case of SampleSceneMRTK) - only 1 scene was selected for each builds I created.

I was wondering if I shall see the 2 virtual displays (which can be seen on the demo video) anyway, even if somehow the tool with the markers is not tracked? Is it possible that it somehow cannot track the tool with the marker (it was printed using white filament)? I mean is there any "signs" that could ensure me if the project was build and deployed in the proper way and I have issue only with the 3d printed tool?

**Comment by hiqb217** [comment]
Hi, to answer your question yes, you should be able to see the two virtual displays which show a live feed of the sensor data.

If the two virtual displays are just black squares and show no sensor data, then it would seem something is going wrong with accessing the Research Mode API. 

Could you confirm what it is you see when you boot up the app on the HoloLens?

**Comment by bolebalazs** [comment]
Here you can find a video about booting up the app on HL: https://drive.google.com/file/d/1TVOQdaAonN74xbNnpxhfmbz7vhoPfsef/view?usp=drive_link. (I hope this link works for you)

I also just put a cube into the scene, but I cannot see the cube neither, so most probably I don't have the issue with Research Mode API, but building/deploying the project.

Tomorrow I will try to document the process how I build and deploy the project to HL.

**Comment by bolebalazs** [comment]
Hi, I just created a document where I collected all of the detailed information (with screenshots as well) how I am creating build and deploy from the beginning, step by step. It would be really appreciated if you could take a look on that. Thanks in advance.

You can find the document here: https://docs.google.com/document/d/1UUO9Xorp6yaUpp2Pnqrz6FcOOfMrEO1Z/edit?usp=drive_link&ouid=113875992091905644720&rtpof=true&sd=true

**Comment by hiqb217** [comment]
Closing this issue after contacting the author directly, who was able to successfully compile and run DINO-Unity using the [unity-19](https://github.com/HL2-DINO/DINO-Unity/tree/unity-19) and [unity-20](https://github.com/HL2-DINO/DINO-Unity/tree/unity-20) branches.

There appears to be some sort of issue encountered with OpenXR, which I haven't yet been able to isolate, and seems to affect users in a seemingly random way, e.g. several others have been able to successfully build and run the `unity-21` branch . 

Relevant part of the Unity player log:

```
[Subsystems] Loading plugin UnityOpenXR for subsystem OpenXR Display...
[XR] Error loading subsystem: Display (1) (header mismatch?)
[Subsystems] Failed to initialize subsystem OpenXR Display [error: 1]
[XR] [2764] [11:19:06.237][Error  ] xrPollEvent: XR_ERROR_FUNCTION_UNSUPPORTED
[XR] [2764] [11:19:06.241][Info   ] 

==== Start Unity OpenXR Diagnostic Report ====

[XR] [2764] [11:19:06.242][Info   ] ==== Report Reason: System Shutdown ====

[XR] [2764] [11:19:06.242][Info   ] ==== OpenXR Init Info ====
[XR] [2764] [11:19:06.242][Info   ] 
[XR] [2764] [11:19:06.242][Info   ] Stage 1 Missing Entry Points: (1)
[XR] [2764] [11:19:06.242][Info   ]   xrInitializeLoaderKHR
[XR] [2764] [11:19:06.242][Info   ] 
[XR] [2764] [11:19:06.242][Info   ] ==== OpenXR Provider Info ====
```

If anyone is able to provide further insight please leave a comment! For others who may experience a similar bug, it is recommended to double check your install setup matches those in the project requirements and to try building either of the Unity 19 or Unity 20 branches.

**Comment by hiqb217** [comment]
Re-opening and closing this issue as the original poster has found a solution.

It appears to be a version compatibility issue for OpenXR. From the issue author:

> I just went to Package Manager (in the scene) and changed the OpenXR version from 1.11.0 to 1.7.0. And it resolved the problem we had earlier.

[This tutorial](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/mixed-reality-openxr-plugin) shows how OpenXR was added using the Mixed Reality Feature Tool. To others experiencing a similar issue on Unity 2021, please try and check the version of the OpenXR plugin to see if this is consistent with your setup.
