### ISSUE TITLE
Expected Results w/ Unmodified Code

### ISSUE THREAD

**Issue by joseerosset** [HL2-DINO/DINO-Unity#3]
Hello!

I believe I have successfully launched the SampleSceneMRTK.scene to my HoloLens 2. I am seeing a debug text canvas, the sensor data display and the ''this is a very long text explaining...''.

I fabricated a test tool model by printing the specs sheet on stiff paper and placing IR stickers where needed. So essentially a paper version of your 3d printed model. 

When I view this model through the app and watch the sensor data screen I see X's appearing on the IR stickers as I move it around, however I never see the green holograms of the tools as seen in the provided GIF. Is this expected with the unmodified code?

I am assuming at the moment it is a problem with my test "model", however I just wanted to confirm that the green hologram should appear on the tracked tool in the code as you've posted it. 

Thank you!

**Comment by hiqb217** [comment]
Hi! 

This is a bit of a strange sounding bug, and also certainly a unique way to try and fabricate the tools! Just to double check, did you just directly print out the specs sheets from the [DINO-IR-Tools/drawings](https://github.com/HL2-DINO/DINO-IR-Tools/tree/main/drawings) folder, and put IR stickers on this drawing? Just double checking, as these are not to scale! 

From memory, crosses are drawn on the sensor images from the DLL side, if a tool is detected, so I would have expected there to be spheres rendered at the center of each of your IR stickers, as well as the green model to show up. 

Another thing you could do is to check the debug canvas on the left of the sensor screen, which should print out the 4x4 transform matrix for both tools. If the tool is successfully detected, it should update the transform matrices. These are printed out in world frame coordinates (which should be the pose of the headset when the app is first launched). You could potentially try to read these values when running the app to see if they're printing sensible results. 

But yes, from memory the green hologram should appear on top of the tools, and also little white spheres should be appearing on the marker centres.
