### ISSUE TITLE
Calculate tracking accuracy

### ISSUE THREAD

**Issue by Nacy09** [HL2-DINO/DINO-Unity#5]
Hi!
I only have HoloLens2 devices. How can I calculate the tracking accuracy?
Also, does the code use the Kalman filter algorithm? I don't see a file with the Kalman filter code.Is there any code that references the Kalman filter algorithm?
Any suggestions would be greatly appreciated.
Thank you!

**Comment by hiqb217** [comment]
Hi @Nacy09,

1) For calculating tracking accuracy, I'd recommend using another device (a separate infrared tracker) or another modality (perhaps visual light markers?) to produce a control to measure against

2) at the moment there is no integrated Kalman filtering, this is left to the user to integrate an existing solution on either the Unity or C++ side. I'd suggest looking through existing implementations, you could even look at OpenCV's Kalman filter as OpenCV is integrated into DINO DLL already

3) Could I please ask you to update the other issue you opened: https://github.com/HL2-DINO/DINO-Unity/issues/2
