### ISSUE TITLE
App crashed after using live preview or media capture. What can I do with it?

### ISSUE THREAD

**Issue by catnull-dev** [HL2-DINO/DINO-Unity#6]
When I run your application in Hololens 2 (without changes and with capabilities for RM) - application crashed and without capture image. Help please! :(

**Comment by hiqb217** [comment]
Hi! Sorry I'm a little unclear from your message. From the title of the issue, it seems the app crashes only when you try and do a live preview (via the Device Portal I guess)?

Or is the app just crashing in general when you try to launch it?

Could you let me know:
- which branch you're trying to build
- what version of Visual Studio you used to build 
- if you've configured the appxmanifest as instructed?

Thanks

**Comment by catnull-dev** [comment]
The app works and Research mode works too. When I turn on the Live preview or take a picture, for example through the built-in function in Hololens, the application crashes. I am building the main branch of 2020, Visual Studio 2022, I carried out the configuration in accordance with the instructions

**Comment by catnull-dev** [comment]
After update system my app is working. Thanks!
