### ISSUE TITLE
Using passive marker spherers

### ISSUE THREAD

**Issue by Walidkilas** [HL2-DINO/DINO-Unity#7]
how can i modify this script to use spheres instead of flat markers ? Thanks for your support !

**Comment by hiqb217** [comment]
Hi, at the moment this is an unsupported feature. I'm trying to find time to implement this nicely with the rest of the code, this comment on another issue is a good starting point:

https://github.com/HL2-DINO/DINO-Unity/issues/4#issuecomment-2202594904

**Comment by hiqb217** [comment]
Hi @Walidkilas, closing this issue, please see https://github.com/HL2-DINO/DINO-Unity/issues/8 for instructions on a new update about using spherical markers with the app. Hope this helps!
